site_name: shenghaiyang
site_url: https://shenghaiyang.github.io/

theme:
  name: material
  language: zh

copyright: Copyright &copy; 2021 盛海洋

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/shenghaiyang
      name: shenghaiyang
  generator: true

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets